# package name
name: !!package!!
# package display name
displayName: !!display!!
# package description
description: !!description!!
# repository url
repoUrl: 'https://github.com/AppalachiaInteractive/!!package!!'
# forked repository url
parentRepoUrl: null
# spdx license id
licenseSpdxId: !!licenseid!!
# license name
licenseName: !!license!!
# list of topic slugs
topics:
  - utilities
# Filter Git tags based on prefix. Used by monorepos to separate pacakges
gitTagPrefix: ''
# A regular expression to ignore Git tags
gitTagIgnore: ''
# Minimal version to build
minVersion: '0.2.0'
# featured image
image: 'https://github.com/AppalachiaInteractive/!!package!!/raw/main/media/icon_social.png'
# featured image fit mode: cover (default) or contain
imageFit: cover
# readme path
readme: 'main:README.md'
# package hunter name (github username)
hunter: ChristopherSchubert